CREATE TABLE METUSER.ROLE (
ROLEID NUMBER NOT NULL PRIMARY KEY,
ROLENAME VARCHAR2(15 CHAR) NOT NULL UNIQUE,
ROLEDESC VARCHAR2(100 CHAR) NOT NULL,
CREATEDDATETIME DATE DEFAULT CURRENT_DATE NOT NULL,
ACTIVE CHAR(1 CHAR) NOT NULL,
LASTMODIFIEDDATETIME DATE DEFAULT CURRENT_DATE NOT NULL,
LASTMODIFIEDSIGNON VARCHAR2(50 CHAR) DEFAULT USER NOT NULL
);