CREATE TABLE METUSER.USER_ROLE (
USERROLEID NUMBER NOT NULL PRIMARY KEY,
USERID NUMBER NOT NULL,
ROLEID NUMBER NOT NULL
);

CREATE UNIQUE INDEX IDX_USERROLE_UNIQUE ON METUSER.USER_ROLE(USERID,ROLEID);

ALTER TABLE METUSER.USER_ROLE ADD CONSTRAINT FK_USER_ROLE1 FOREIGN KEY (USERID) REFERENCES METUSER.USER_DETAIL(USERID);

ALTER TABLE METUSER.USER_ROLE ADD CONSTRAINT FK_USER_ROLE2 FOREIGN KEY (ROLEID) REFERENCES METUSER.ROLE(ROLEID);