CREATE TABLE METUSER.ROLE_DET (
  ROLE_ID NUMBER NOT NULL PRIMARY KEY,
  ROLE VARCHAR2(255) DEFAULT NULL
);

CREATE TABLE METUSER.USER_DET (
  USER_ID NUMBER NOT NULL PRIMARY KEY,
  ACTIVE NUMBER DEFAULT NULL,
  EMAIL VARCHAR2(255) NOT NULL,
  LAST_NAME VARCHAR2(255) NOT NULL,
  NAME VARCHAR2(255) NOT NULL,
  PASSWORD VARCHAR2(255) NOT NULL
);

CREATE TABLE METUSER.USER_ROLE (
  USER_ID NUMBER NOT NULL,
  ROLE_ID NUMBER NOT NULL,
  CONSTRAINT USER_ROLE_PK PRIMARY KEY (USER_ID,ROLE_ID);
);

ALTER TABLE METUSER.USER_ROLE ADD CONSTRAINT FK_USER_ROLE1 FOREIGN KEY (USER_ID) REFERENCES METUSER.USER_DET(USER_ID);

ALTER TABLE METUSER.USER_ROLE ADD CONSTRAINT FK_USER_ROLE2 FOREIGN KEY (ROLE_ID) REFERENCES METUSER.ROLE_DET(ROLE_ID);

INSERT INTO METUSER.ROLE_DET VALUES (1,'ADMIN');