CREATE TABLE METUSER.USER_CREDENTIAL (
CREDENTIALID NUMBER NOT NULL PRIMARY KEY,
USERID NUMBER NOT NULL,
PASSWORD VARCHAR2(100 CHAR) NOT NULL,
STATUS VARCHAR2(25 CHAR) NOT NULL,
EXPIREDON DATE NOT NULL,
LASTMODIFIEDDATETIME DATE DEFAULT CURRENT_DATE NOT NULL,
LASTMODIFIEDSIGNON VARCHAR2(50 CHAR) DEFAULT USER NOT NULL
);

CREATE UNIQUE INDEX IDX_USERCREDENTIAL_UNIQUE ON METUSER.USER_CREDENTIAL(CREDENTIALID,USERID);

ALTER TABLE METUSER.USER_CREDENTIAL ADD CONSTRAINT FK_USER_CREDENTIAL FOREIGN KEY (USERID) REFERENCES METUSER.USER_DETAIL(USERID);