CREATE OR REPLACE PACKAGE METUSER.METRO_USER_SECURITY AS

	PROCEDURE PKG_ADD_USER (P_USERID IN NUMBER, P_PASSWORD IN VARCHAR2);

	PROCEDURE PKG_CHANGE_PASSWORD (P_USERID IN NUMBER, P_OLD_PASSWORD IN VARCHAR2, P_NEW_PASSWORD IN VARCHAR2);

	FUNCTION FN_VALID_USER (P_USERID IN NUMBER, P_PASSWORD IN VARCHAR2) RETURN VARCHAR2;

END;
/